default:
  image: "ubuntu:22.04"

before_script:
  - apt-get update
  - apt-get -y install software-properties-common sudo g++
  - apt-get -y install pip vim
  - apt-get -y install libgsl-dev git
  - python3 --version
  - pip3 install numpy
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt

stages:
  - Static Analysis
  - Test

black:
  stage: Static Analysis
  script:
  - black --check --config pyproject.toml .

flake8:
  stage: Static Analysis
  script:
  - flake8

pytest:
  stage: Test
  script:
  - python3 -m pytest -v
